export const DEFAULT_FIRST_STAGE = 0;
export const DEFAULT_STAGE_COUNT = 1;
export const DEFAULT_LAST_STAGE = DEFAULT_STAGE_COUNT - 1;
export const DEFAULT_ITEMS_PER_STAGE = 6;
export const DEFAULT_TOTAL_ITEMS = DEFAULT_STAGE_COUNT * DEFAULT_ITEMS_PER_STAGE;
export const MATCH_RESET_TIMEOUT_DELAY = 300;
